-- Technode VPS baseline schema

CREATE TABLE IF NOT EXISTS customers (
	customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_name VARCHAR(100),
	customer_representative VARCHAR(100),
	email VARCHAR(100),
	phone VARCHAR(20),
	remark VARCHAR(255),
	password VARCHAR(255)
);

-- Ensure customer_id uses identity even if table existed before this file.
DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'customers'
		  AND column_name = 'customer_id'
		  AND is_identity = 'NO'
	) THEN
		ALTER TABLE customers
		ALTER COLUMN customer_id
		ADD GENERATED BY DEFAULT AS IDENTITY;
	END IF;
END $$;

