-- Technode VPS baseline schema

CREATE TABLE IF NOT EXISTS companies (
	company_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	slug VARCHAR(100) NOT NULL UNIQUE,
	login_image_path VARCHAR(255) NOT NULL,
	sidebar_image_path VARCHAR(255) NOT NULL,
	browser_icon_path VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
	customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id INT NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
	customer_representative VARCHAR(100),
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20),
	remark VARCHAR(255),
	password VARCHAR(255),
	UNIQUE(company_id, email)
);

-- Ensure customer_id uses identity even if table existed before this file.
DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_name = 'customers'
		  AND column_name = 'customer_id'
		  AND is_identity = 'NO'
	) THEN
		ALTER TABLE customers
		ALTER COLUMN customer_id
		ADD GENERATED BY DEFAULT AS IDENTITY;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_customers_company_id ON customers(company_id);

CREATE TABLE IF NOT EXISTS ems_units (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	unit_id VARCHAR(64) UNIQUE NOT NULL,
	customer_id INT NULL REFERENCES customers(customer_id) ON DELETE SET NULL,
	location_label VARCHAR(120),
	latitude DECIMAL(10, 6),
	longitude DECIMAL(10, 6),
	device_type VARCHAR(120),
	topic_path VARCHAR(255),
	last_seen_at TIMESTAMP,
	last_status VARCHAR(16),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ems_units_customer_id ON ems_units(customer_id);
CREATE INDEX IF NOT EXISTS idx_ems_units_last_seen_at ON ems_units(last_seen_at);

CREATE TABLE IF NOT EXISTS ems_logs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ems_unit_id BIGINT NOT NULL REFERENCES ems_units(id) ON DELETE CASCADE,
	message_type VARCHAR(16) NOT NULL,
	status_value VARCHAR(16),
	device_timestamp TIMESTAMP NOT NULL,
	raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
	meter_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ems_logs_unit_timestamp
	ON ems_logs(ems_unit_id, device_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_ems_logs_created_at
	ON ems_logs(created_at);
