DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'customers'
          AND column_name = 'customer_id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
