DROP TABLE IF EXISTS "ems_logs";
DROP TABLE IF EXISTS "ems_units";
DROP TABLE IF EXISTS "customers";
DROP TABLE IF EXISTS "companies";

CREATE TABLE "companies" (
    "company_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "slug" VARCHAR(100) NOT NULL,
    "logo_path" VARCHAR(255) NOT NULL,
    "icon_path" VARCHAR(255) NOT NULL,
    "white_label_settings" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "companies_slug_key" ON "companies"("slug");

CREATE TABLE "customers" (
    "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "company_id" INTEGER NOT NULL,
    "customer_representative" VARCHAR(100),
    "email" VARCHAR(100) NOT NULL,
    "phone" VARCHAR(20),
    "remark" VARCHAR(255),
    "password" VARCHAR(255),
    CONSTRAINT "customers_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("company_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "customers_company_id_email_key" ON "customers"("company_id", "email");
CREATE INDEX "customers_company_id_idx" ON "customers"("company_id");

CREATE TABLE "ems_units" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "unit_id" VARCHAR(64) NOT NULL,
    "customer_id" INTEGER,
    "location_label" VARCHAR(120),
    "latitude" DECIMAL(10, 6),
    "longitude" DECIMAL(10, 6),
    "device_type" VARCHAR(120),
    "last_seen_at" TIMESTAMP(3),
    "topic_path" VARCHAR(255),
    "unit_field_template" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "rtu_overrides" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ems_units_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("customer_id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "ems_units_unit_id_key" ON "ems_units"("unit_id");
CREATE INDEX "ems_units_customer_id_idx" ON "ems_units"("customer_id");
CREATE INDEX "ems_units_last_seen_at_idx" ON "ems_units"("last_seen_at");

CREATE TABLE "ems_logs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ems_unit_id" BIGINT NOT NULL,
    "device_timestamp" TIMESTAMP(3) NOT NULL,
    "raw_unit_payload" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "raw_rtu_array" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "mapped_rtu_array" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ems_logs_ems_unit_id_fkey" FOREIGN KEY ("ems_unit_id") REFERENCES "ems_units"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "ems_logs_ems_unit_id_device_timestamp_idx" ON "ems_logs"("ems_unit_id", "device_timestamp" DESC);
CREATE INDEX "ems_logs_created_at_idx" ON "ems_logs"("created_at");

INSERT INTO "companies" ("name", "slug", "logo_path", "icon_path")
VALUES ('Technode', 'technode', 'companies/technode/logo.png', 'companies/technode/icon.png');

INSERT INTO "customers" ("company_id", "customer_representative", "email", "phone", "remark", "password")
SELECT "company_id", 'Russel', 'russ@gmail.com', NULL, 'Seeded default customer', 'russ123'
FROM "companies"
WHERE "slug" = 'technode';
